version: "3.7"

services:
  web:
    container_name: "webapi"
    image: "treninidotnet"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
    networks:
      - webapi-network

  postgres:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_USER: tdbuser
      POSTGRES_PASSWORD: tdbpass
    networks:
      - webapi-network

networks:
  webapi-network:
    driver: bridge
