//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreniniDotNet.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreniniDotNet.Domain.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand name must be non empty.
        /// </summary>
        internal static string InvalidBrandName {
            get {
                return ResourceManager.GetString("InvalidBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gauge value must be positive.
        /// </summary>
        internal static string InvalidGaugeValue {
            get {
                return ResourceManager.GetString("InvalidGaugeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemNumber value must be non null and non empty.
        /// </summary>
        internal static string InvalidItemNumber {
            get {
                return ResourceManager.GetString("InvalidItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid length: it cannot be negative.
        /// </summary>
        internal static string InvalidLengthNegativeValue {
            get {
                return ResourceManager.GetString("InvalidLengthNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to railway name must be non empty.
        /// </summary>
        internal static string InvalidRailwayName {
            get {
                return ResourceManager.GetString("InvalidRailwayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid railway: operating until has a value for an active railway.
        /// </summary>
        internal static string InvalidRailwayOperatingUntilForInactiveRailway {
            get {
                return ResourceManager.GetString("InvalidRailwayOperatingUntilForInactiveRailway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid railway: operating since &gt; operating until.
        /// </summary>
        internal static string InvalidRailwaySinceLaterThanOperatingUntil {
            get {
                return ResourceManager.GetString("InvalidRailwaySinceLaterThanOperatingUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scale name must be non empty.
        /// </summary>
        internal static string InvalidScaleName {
            get {
                return ResourceManager.GetString("InvalidScaleName", resourceCulture);
            }
        }
    }
}
