name: TreniniDotNet / CI workflow

on: 
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - Src/**
      - Tests/**
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    
    - name: Build with dotnet
      run: dotnet build TreniniDotNet.sln --configuration Release
    
    - name: Run the Tests
      run: dotnet test TreniniDotNet.sln --configuration Release

    - name: Generate coverage report
      run: dotnet test TreniniDotNet.sln /p:CollectCoverage=true /p:CoverletOutput=../../TestResults/ /p:CoverletOutputFormat=lcov /maxcpucount:1
      
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: TestResults/coverage.info  
